# **🧠 Llumo Agent-Based Function Calling & Evluation**


---

This notebook helps you create functional agents, then run and evaluate them using the Llumo evaluation framework. It allows you to:

- **Define custom agents using Python functions**

- **Register them with the LlumoAgent class**

- **Process natural language queries using OpenAI or Google**

- **Automatically route queries to relevant agents**

- **Generate and evaluate responses using the LlumoClient**


---

📦 Install and Import Required Libraries

In [ ]:
!pip install llumo -quiet

In [ ]:
# Importing necessary libraries
import pandas as pd

# Llumo package imports
import llumo
from llumo import LlumoClient
from llumo.functionCalling import LlumoAgent

# ⚛ **Defining Tools**

In [ ]:
# 👋 Greeting Function
def greetUser(name, greeting):
    return {"message": f"{greeting}, {name}!"}

# 💰 Company Details Function
def companyDetails(companyName):
    companyData = {
        "Reliance": {
            "industry": "Conglomerate",
            "employees": "340,000",
            "headquarters": "Mumbai, India",
            "profit": "1.2 billion USD"
        },
        "Google": {
            "industry": "Technology",
            "employees": "190,000",
            "headquarters": "Mountain View, California",
            "profit": "85 billion USD"
        },
        "Meta": {
            "industry": "Social Media",
            "employees": "71,000",
            "headquarters": "Menlo Park, California",
            "profit": "39.1 billion USD"
        },
        "Amazon": {
            "industry": "E-commerce & Cloud",
            "employees": "1,500,000",
            "headquarters": "Seattle, Washington",
            "profit": "33.3 billion USD"
        },
        "TCS": {
            "industry": "IT Services",
            "employees": "616,000",
            "headquarters": "Mumbai, India",
            "profit": "25.4 billion USD"
        }
    }

    return {"message": companyData.get(companyName, {"message": "Company details not available"})}


# 👨‍💼 Employee Details Function (with dummy data)
def employeeDetails(employeeName):
    employeeData = {
        "Amit Sharma": {
            "position": "Software Engineer",
            "department": "IT",
            "salary": "₹12,00,000",
            "email": "amit.sharma@example.com"
        },
        "Rina Verma": {
            "position": "Data Analyst",
            "department": "Analytics",
            "salary": "₹10,00,000",
            "email": "rina.verma@example.com"
        },
        "John Doe": {
            "position": "Project Manager",
            "department": "Operations",
            "salary": "₹18,00,000",
            "email": "john.doe@example.com"
        },
        "Neha Kapoor": {
            "position": "HR Executive",
            "department": "HR",
            "salary": "₹9,00,000",
            "email": "neha.kapoor@example.com"
        },
        "Rajiv Mehra": {
            "position": "DevOps Engineer",
            "department": "IT",
            "salary": "₹13,50,000",
            "email": "rajiv.mehra@example.com"
        }
    }
    return {"message":employeeData.get(employeeName, {"message": "Employee not found"})}

# 🍽️ Restaurant Details Function (with dummy data)
def restaurantDetails(restaurantName):
    restaurantData = {
        "Spice Villa": {
            "cuisine": "Indian",
            "location": "Mumbai",
            "rating": "4.5",
            "contact": "+91-9988776655"
        },
        "Sushi Hub": {
            "cuisine": "Japanese",
            "location": "Delhi",
            "rating": "4.7",
            "contact": "+91-8877665544"
        },
        "Burger Town": {
            "cuisine": "Fast Food",
            "location": "Bangalore",
            "rating": "4.2",
            "contact": "+91-7766554433"
        },
        "The Italian Bowl": {
            "cuisine": "Italian",
            "location": "Chennai",
            "rating": "4.6",
            "contact": "+91-6655443322"
        },
        "Tandoori Flames": {
            "cuisine": "North Indian",
            "location": "Hyderabad",
            "rating": "4.4",
            "contact": "+91-5544332211"
        }
    }
    return restaurantData.get(restaurantName, {"message": "Restaurant not found"})

# 📚**Agent Registration**

In [ ]:

greetAgent = LlumoAgent(
    name="greetUser",
    description="Greets a user with a custom message",
    parameters={
        "name": {"type": "string", "description": "Name of the user to greet"},
        "greeting": {"type": "string", "description": "Greeting message"}
    },
    function=greetUser
)


employeeAgent = LlumoAgent(
    name="employeeDetails",
    description="Returns dummy employee details for a given name",
    parameters={
        "employeeName": {"type": "string", "description": "Name of the employee"}
    },
    function=employeeDetails
)

restaurantAgent = LlumoAgent(
    name="restaurantDetails",
    description="Returns dummy restaurant details for a given restaurant",
    parameters={
        "restaurantName": {"type": "string", "description": "Name of the restaurant"}
    },
    function=restaurantDetails
)

companyAgent = LlumoAgent(
    name="companyDetails",
    description="Returns detailed company information including industry, employees, HQ, and profit",
    parameters={
        "companyName": {"type": "string", "description": "Name of the company"}
    },
    function=companyDetails
)

print("✅ All agents created successfully")

✅ All agents created successfully

#📝 **Dummy Queries for Evaluation**

In [ ]:
# Dummy query dataframe
df = pd.DataFrame({
    "query": [
        "Can you greet Rina with a Good morning?",
        "Book a flight for new delhi for today at 2:00 PM."
        "What's the profit of OpenAI?",
        "Tell me Meta's latest profit",
        "What does Rina Verma do?",
        "Give me details of Spice Villa restaurant",
        "Hello, How are you?",
        "How much profit did Amazon make, and please book a flight for new delhi for today at 2:00 PM.",
        "I want to know the position of Amit Sharma.",
        "Tell me about Burger Town's cuisine and location. And, book a table for me for today's evening.",
        "Could you say hi to Neha in a friendly way?",
        "Share the profit of Google.",
        "Give me some info about Sushi Hub.",
        "Do you know what John Doe, and Ashish Mehra does. ?",
        "What's the department of Rina Verma?",
        "Greet Priya with a warm welcome message.",
        "What's the revenue of Reliance and TATA ?",
        "Tell me where Burger Town is located.",
        "Say Namaste to Rahul.",
        "Details of a restaurant called Sushi Hub, please."
    ]
})

# 🔐 **Keys Setup & Output Generation**
- Setting up the Open AI key
- Setting up Llumo Client
- Output Generation & Llumo Generation

In [ ]:
# OpenAI and Llumo API Keys
openaiKey = "Enter Your Open AI Api Key Here"  # Replace with your OpenAI Key

# Replace with your Llumo api key
client = LlumoClient(api_key="Enter Your Llumo AI Key Here")


# Evaluate queries using registered agents
agents = [greetAgent, companyAgent, employeeAgent, restaurantAgent]

print("🚀 Starting for Output Generation & Evaluation...")
results = client.evaluateAgents(df, model="openai", agents=agents, model_api_key=openaiKey)

# Display results
result_df = results

🚀 Starting for Output Generation & Evaluation...

======= Running evaluation for: Tool Reliability =======

======= Running evaluation for: Stepwise Progression =======

======= Running evaluation for: Tool Selection Accuracy =======

======= Running evaluation for: Final Task Alignment =======

# 📑 **Result DataFrame**

In [ ]:
result_df

,query,output,messageHistory,tools,Tool Reliability,Stepwise Progression,Tool Selection Accuracy,Final Task Alignment
0,Can you greet Rina with a Good morning?,"Good morning, Rina!","[{'role': 'user', 'content': 'Can you greet Ri...",{'greetUser': 'Greets a user with a custom mes...,100,100,100,99
1,Book a flight for new delhi for today at 2:00 ...,"I'm sorry, but as an artificial intelligence, ...","[{'role': 'user', 'content': ""Book a flight fo...",{'greetUser': 'Greets a user with a custom mes...,2,2,2,2
2,Tell me Meta's latest profit,Meta's latest profit is 39.1 billion USD.,"[{'role': 'user', 'content': ""Tell me Meta's l...",{'greetUser': 'Greets a user with a custom mes...,99,99,99,99
3,What does Rina Verma do?,Rina Verma works as a Data Analyst in the Anal...,"[{'role': 'user', 'content': 'What does Rina V...",{'greetUser': 'Greets a user with a custom mes...,100,100,100,99
4,Give me details of Spice Villa restaurant,Spice Villa is an Indian restaurant located in...,"[{'role': 'user', 'content': 'Give me details ...",{'greetUser': 'Greets a user with a custom mes...,99,99,99,99
5,"Hello, How are you?","Hello! I'm an AI and don't have feelings, but ...","[{'role': 'user', 'content': 'Hello, How are y...",{'greetUser': 'Greets a user with a custom mes...,1,1,1,99
6,"How much profit did Amazon make, and please bo...","In 2020, Amazon made a profit of 33.3 billion ...","[{'role': 'user', 'content': 'How much profit ...",{'greetUser': 'Greets a user with a custom mes...,15,15,15,1
7,I want to know the position of Amit Sharma.,Amit Sharma is a Software Engineer in the IT d...,"[{'role': 'user', 'content': 'I want to know t...",{'greetUser': 'Greets a user with a custom mes...,100,100,100,100
8,Tell me about Burger Town's cuisine and locati...,Burger Town is a popular Fast Food restaurant ...,"[{'role': 'user', 'content': ""Tell me about Bu...",{'greetUser': 'Greets a user with a custom mes...,99,99,99,2
9,Could you say hi to Neha in a friendly way?,"Hi, Neha! How's it going?","[{'role': 'user', 'content': 'Could you say hi...",{'greetUser': 'Greets a user with a custom mes...,100,100,100,100
10,Share the profit of Google.,The profit of Google is approximately 85 billi...,"[{'role': 'user', 'content': 'Share the profit...",{'greetUser': 'Greets a user with a custom mes...,99,99,99,100
11,Give me some info about Sushi Hub.,Sushi Hub is a Japanese restaurant located in ...,"[{'role': 'user', 'content': 'Give me some inf...",{'greetUser': 'Greets a user with a custom mes...,100,100,99,100
12,"Do you know what John Doe, and Ashish Mehra do...",John Doe works as a Project Manager in the Ope...,"[{'role': 'user', 'content': 'Do you know what...",{'greetUser': 'Greets a user with a custom mes...,100,100,57,99
13,What's the department of Rina Verma?,Rina Verma is part of the Analytics department.,"[{'role': 'user', 'content': ""What's the depar...",{'greetUser': 'Greets a user with a custom mes...,100,100,100,100
14,Greet Priya with a warm welcome message.,"Welcome, we're so glad to have you here!, Priya!","[{'role': 'user', 'content': 'Greet Priya with...",{'greetUser': 'Greets a user with a custom mes...,100,100,100,99
15,What's the revenue of Reliance and TATA ?,Reliance's revenue field was not available in ...,"[{'role': 'user', 'content': ""What's the reven...",{'greetUser': 'Greets a user with a custom mes...,20,20,32,1
16,Tell me where Burger Town is located.,Burger Town is located in Bangalore. You can c...,"[{'role': 'user', 'content': 'Tell me where Bu...",{'greetUser': 'Greets a user with a custom mes...,100,100,100,99
17,Say Namaste to Rahul.,"Namaste, Rahul!","[{'role': 'user', 'content': 'Say Namaste to R...",{'greetUser': 'Greets a user with a custom mes...,99,99,100,100
18,"Details of a restaurant called Sushi Hub, please.",Sushi Hub is a Japanese restaurant located in ...,"[{'role': 'user', 'content': 'Details of a res...",{'greetUser': 'Greets a user with a custom mes...,100,100,99,100

# **Demo Result Table**

In [ ]:
demo_df = result_df.copy()
demo_df

,query,output,messageHistory,tools,Tool Reliability,Stepwise Progression,Tool Selection Accuracy,Final Task Alignment
0,Can you greet Rina with a Good morning?,"Good morning, Rina!","[{'role': 'user', 'content': 'Can you greet Ri...",{'greetUser': 'Greets a user with a custom mes...,100,100,100,99
1,Book a flight for new delhi for today at 2:00 ...,"I'm sorry, but as an artificial intelligence, ...","[{'role': 'user', 'content': ""Book a flight fo...",{'greetUser': 'Greets a user with a custom mes...,2,2,2,2
2,Tell me Meta's latest profit,Meta's latest profit is 39.1 billion USD.,"[{'role': 'user', 'content': ""Tell me Meta's l...",{'greetUser': 'Greets a user with a custom mes...,99,99,99,99
3,What does Rina Verma do?,Rina Verma works as a Data Analyst in the Anal...,"[{'role': 'user', 'content': 'What does Rina V...",{'greetUser': 'Greets a user with a custom mes...,100,100,100,99
4,Give me details of Spice Villa restaurant,Spice Villa is an Indian restaurant located in...,"[{'role': 'user', 'content': 'Give me details ...",{'greetUser': 'Greets a user with a custom mes...,99,99,99,99
5,"Hello, How are you?","Hello! I'm an AI and don't have feelings, but ...","[{'role': 'user', 'content': 'Hello, How are y...",{'greetUser': 'Greets a user with a custom mes...,1,1,1,99
6,"How much profit did Amazon make, and please bo...","In 2020, Amazon made a profit of 33.3 billion ...","[{'role': 'user', 'content': 'How much profit ...",{'greetUser': 'Greets a user with a custom mes...,15,15,15,1
7,I want to know the position of Amit Sharma.,Amit Sharma is a Software Engineer in the IT d...,"[{'role': 'user', 'content': 'I want to know t...",{'greetUser': 'Greets a user with a custom mes...,100,100,100,100
8,Tell me about Burger Town's cuisine and locati...,Burger Town is a popular Fast Food restaurant ...,"[{'role': 'user', 'content': ""Tell me about Bu...",{'greetUser': 'Greets a user with a custom mes...,99,99,99,2
9,Could you say hi to Neha in a friendly way?,"Hi, Neha! How's it going?","[{'role': 'user', 'content': 'Could you say hi...",{'greetUser': 'Greets a user with a custom mes...,100,100,100,100
10,Share the profit of Google.,The profit of Google is approximately 85 billi...,"[{'role': 'user', 'content': 'Share the profit...",{'greetUser': 'Greets a user with a custom mes...,99,99,99,100
11,Give me some info about Sushi Hub.,Sushi Hub is a Japanese restaurant located in ...,"[{'role': 'user', 'content': 'Give me some inf...",{'greetUser': 'Greets a user with a custom mes...,100,100,99,100
12,"Do you know what John Doe, and Ashish Mehra do...",John Doe works as a Project Manager in the Ope...,"[{'role': 'user', 'content': 'Do you know what...",{'greetUser': 'Greets a user with a custom mes...,100,100,57,99
13,What's the department of Rina Verma?,Rina Verma is part of the Analytics department.,"[{'role': 'user', 'content': ""What's the depar...",{'greetUser': 'Greets a user with a custom mes...,100,100,100,100
14,Greet Priya with a warm welcome message.,"Welcome, we're so glad to have you here!, Priya!","[{'role': 'user', 'content': 'Greet Priya with...",{'greetUser': 'Greets a user with a custom mes...,100,100,100,99
15,What's the revenue of Reliance and TATA ?,Reliance's revenue field was not available in ...,"[{'role': 'user', 'content': ""What's the reven...",{'greetUser': 'Greets a user with a custom mes...,20,20,32,1
16,Tell me where Burger Town is located.,Burger Town is located in Bangalore. You can c...,"[{'role': 'user', 'content': 'Tell me where Bu...",{'greetUser': 'Greets a user with a custom mes...,100,100,100,99
17,Say Namaste to Rahul.,"Namaste, Rahul!","[{'role': 'user', 'content': 'Say Namaste to R...",{'greetUser': 'Greets a user with a custom mes...,99,99,100,100
18,"Details of a restaurant called Sushi Hub, please.",Sushi Hub is a Japanese restaurant located in ...,"[{'role': 'user', 'content': 'Details of a res...",{'greetUser': 'Greets a user with a custom mes...,100,100,99,100