This notebook generates responses for a given prompt using multiple LLM models (GPT-3.5-Turbo, Gemini-Pro, and Text-Bison) via the LLUMO API. The results are stored in a structured Excel sheet.

Step 1: Import Required Libraries

In [29]:
import requests
import pandas as pd
from google.colab import userdata

Step 2: Define API Configuration

In [30]:

LLUMO_API_KEY = userdata.get("LLUMO_API_KEY")
# API Authorization Header (Replace with a valid API key)
headers = {
    "Authorization": f"Bearer {LLUMO_API_KEY}"
}

# API Endpoint
LLUMO_ENDPOINT = "https://model-api.llumo.ai/analytics/get-single-output-analytics"

Step 3: Define Available LLM Models

In [35]:
# List of LLM models to use for generating responses
llm_models = ["gpt-3.5-turbo", "gemini-pro", "text-bison"]

Step 4: Define Prompts for Evaluation

In [38]:
import pandas as pd

# Define different prompt styles to generate child-friendly explanations.
prompt_templates = [
    "Explain {{topic}} in a way that a 10-year-old can understand.",
    "Give a simple and fun explanation of {{topic}} with an example.",
    "Break down {{topic}} into very easy steps for a child."
]

# Define topics for which explanations will be generated.
topics = ["Artificial Intelligence", "Photosynthesis", "Black Holes"]

# Initialize an empty DataFrame to store prompts and model outputs.
data = pd.DataFrame(columns=["Prompt"] + [f"output_{model}" for model in llm_models])
data

Empty DataFrame
Columns: [Prompt, output_gpt-3.5-turbo, output_gemini-pro, output_text-bison]
Index: []

Step 5: Generating the LLM response.

In [52]:
import json
# Iterate through prompt templates to generate explanations.
for indx in range(len(prompt_templates)):
    prompt = prompt_templates[indx]
    topic = topics[indx]  # Extract topic for API input
    finalPrompt = prompt.replace("{{topic}}", topic)

    for model in llm_models:
        payload = {
            "workspaceID": "c38690ce92ba0d88e11b856d",
            "definition": "",
            "analyticsName": "",
            "prompt": finalPrompt,
        }

        try:
            # Send API request
            response = requests.post(url=LLUMO_ENDPOINT, json=payload, headers=headers, timeout=18)
            response_json = response.json()
            llm_output = json.loads(response_json["data"])



            # Append data to DataFrame correctly
            data.loc[indx, "Prompt"] = finalPrompt
            data.loc[indx, f"output_{model}"] = llm_output['output']

            print(f"✅ Successfully fetched response from {model} for the given prompt.")

        except Exception as e:
            print(f"❌ Error fetching response from {model} for the given prompt: {e}")
            continue

✅ Successfully fetched response from gpt-3.5-turbo for the given prompt.
✅ Successfully fetched response from gemini-pro for the given prompt.
✅ Successfully fetched response from text-bison for the given prompt.
✅ Successfully fetched response from gpt-3.5-turbo for the given prompt.
✅ Successfully fetched response from gemini-pro for the given prompt.
✅ Successfully fetched response from text-bison for the given prompt.
✅ Successfully fetched response from gpt-3.5-turbo for the given prompt.
✅ Successfully fetched response from gemini-pro for the given prompt.
✅ Successfully fetched response from text-bison for the given prompt.

In [53]:
# final dataframe
print(data)

,Prompt,output_gpt-3.5-turbo,output_gemini-pro,output_text-bison
0,Explain Artificial Intelligence in a way that ...,Imagine teaching a computer to think like a hu...,Imagine teaching a computer to think like a hu...,Imagine you're teaching a dog a trick. You sh...
1,Give a simple and fun explanation of Photosynt...,Imagine a plant is a tiny chef. Photosynthesi...,Photosynthesis is like a plant's superpower! ...,Imagine a plant is like a tiny chef. Photosyn...
2,Break down Black Holes into very easy steps fo...,1. **Super-duper gravity:** Imagine a star muc...,1. **Super-strong gravity:** Imagine a giant v...,1. **Super-strong gravity:** Imagine a giant v...